<ScreenManagement>:
    transition:
    LoadingScreen:
    HomeScreen:
    ResourceScreen:
    ScreeningToolsScreen:
    AnxietyEDScreen:
    LocalResourcesScreen:
    QuoteScreen:
    Tab:


<LoadingScreen>:
    name: "Load"
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            size: self.size

    Image:
        source: "LoadBackground.png"
        size_hint: 0.3, 0.3
        pos_hint: {"x":0.35, "top":0.65}

    FloatLayout:
        Label:
            text: "BREATHEWELL"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.4}
        Label:
            text: "1 Peter 5:7"
            color: 0,0,0,1
            font_size: '20sp'
            size_hint: 0.05, 0.1
            pos_hint: {"x":0.475, "top":0.09}



<HomeScreen>:
    name: 'Home'
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            size: self.size
    Image:
        source: "verse.jpg"
        size_hint: 1, 0.5
        pos_hint: {"x":0, "top":0.85}

    FloatLayout:
        Label:
            text: "BREATHEWELL"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.99}


    Button:
        text: "Home"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0, "top":0.09}
    Button:
        text: "Resources"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0.33, "top":0.09}
        on_press:
            root.manager.current = "Resources"
            root.manager.transition.direction = "left"

    Button:
        text: "Daily Quote"
        size_hint: 0.335, 0.1
        pos_hint: {"x":0.66, "top":0.09}
        on_press:
            root.manager.current = "Daily Quote"
            root.manager.transition.direction = "left"



<ResourceScreen>:
    name: "Resources"
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            pos:
            size: self.size

    FloatLayout:
        Label:
            name: "screening tools"
            text: "[ref=<str>]Screening Tools[/ref]"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top": 1}
            markup: True
            on_ref_press:
                root.manager.current = "Screening Tools"

        Label:
            name: "anxiety"
            text: "[ref=<str>]What is Anxiety?[/ref]"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top": 0.8}
            markup: True
            on_ref_press:
                root.manager.current = "Anxiety Education"

        Label:
            name: "resources"
            text: "[ref=<str>]Local Resources[/ref]"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.6}
            markup: True
            on_ref_press:
                root.manager.current = "Local Resources"
        Label:
            name: "survey"
            text: "[ref=<str>]App Survey[/ref]"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.4}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://gardnerwebb.pdx1.qualtrics.com/jfe/preview/previewId/b591051a-d5fe-47a0-810a-b2e051921267/SV_cx5fWpMjjbh51no?Q_CHL=preview&Q_SurveyVersionID=current")

    Button:
        text: "Home"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0, "top":0.09}
        on_press:
            root.manager.current = "Home"
            root.manager.transition.direction = "right"

    Button:
        text: "Resources"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0.33, "top":0.09}
    Button:
        text: "Daily Quote"
        size_hint: 0.335, 0.1
        pos_hint: {"x":0.66, "top":0.09}
        on_press:
            root.manager.current = "Daily Quote"
            root.manager.transition.direction = "left"

<ScreeningToolsScreen>
    name: "Screening Tools"
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            pos:
            size: self.size

    Carousel:
        direction: 'bottom'
        size_hint: 1, 0.6
        pos_hint: {"x":0, "top":0.8}
        AsyncImage:
            source: 'GAD-7.jpeg'
        AsyncImage:
            source: 'PHQ-9.png'

    Button:
        text: "Home"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0, "top":0.09}
        on_press:
            root.manager.current = "Home"
    Button:
        text: "Resources"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0.33, "top":0.09}
        on_press:
            root.manager.current = "Resources"
    Button:
        text: "Daily Quote"
        size_hint: 0.335, 0.1
        pos_hint: {"x":0.66, "top":0.09}
        on_press:
            root.manager.current = "Daily Quote"

<AnxietyEDScreen>:
    name: "Anxiety Education"
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            pos:
            size: self.size

    Image:
        source: "LoadBackground.png"
        size_hint: 0.3, 0.3
        pos_hint: {"x":0.35, "top":0.65}

    FloatLayout:
        Label:
            text: "Anxiety Management (YouTube Links)"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top": 1}
        Label:
            text: "Binaural Beats"
            color: 0,0,0,1
            font_size: '24sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.25, "top":0.9}
        Label:
            text: "[ref=<str>][u] https://www.youtube.com/watch?v=xsfyb1pStdw[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.25, "top":0.8}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.youtube.com/watch?v=xsfyb1pStdw")
        Label:
            text: "[ref=<str>][u]https://www.youtube.com/watch?v=JP3R00tCL4I[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.25, "top":0.7}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.youtube.com/watch?v=JP3R00tCL4I")
        Label:
            text: "Mindfulness/Meditation"
            color: 0,0,0,1
            font_size: '24sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.6, "top":0.9}
        Label:
            text: "[ref=<str>][u]https://www.youtube.com/watch?v=ZToicYcHIOU[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.6, "top":0.8}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.youtube.com/watch?v=ZToicYcHIOU")
        Label:
            text: "[ref=<str>][u]https://www.youtube.com/watch?v=Xl_B45DpMLU[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.6, "top":0.7}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.youtube.com/watch?v=Xl_B45DpMLU")

        Label:
            text: "Understanding Anxiety ppt"
            color: 0,0,0,1
            font_size: '20sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x": 0.45, "top": 0.6}


    Carousel:
        direction: 'bottom'
        size_hint: 1, 0.5
        pos_hint: {"x":0, "top":0.5}
        AsyncImage:
            source: 'pptImages\slide-1.png'
        AsyncImage:
            source: 'pptImages\slide-2.png'
        AsyncImage:
            source: 'pptImages\slide-3.png'
        AsyncImage:
            source: 'pptImages\slide-4.png'
        AsyncImage:
            source: 'pptImages\slide-5.png'
        AsyncImage:
            source: 'pptImages\slide-6.png'
        AsyncImage:
            source: 'pptImages\slide-7.png'
        AsyncImage:
            source: 'pptImages\slide-8.png'
        AsyncImage:
            source: 'pptImages\slide-9.png'
        AsyncImage:
            source: 'pptImages\slide-10.png'
        AsyncImage:
            source: 'pptImages\slide-11.png'
        AsyncImage:
            source: 'pptImages\slide-12.png'
        AsyncImage:
            source: 'pptImages\slide-13.png'
        AsyncImage:
            source: 'pptImages\slide-14.png'
        AsyncImage:
            source: 'pptImages\slide-15.png'
        AsyncImage:
            source: 'pptImages\slide-16.png'
        AsyncImage:
            source: 'pptImages\slide-17.png'
        AsyncImage:
            source: 'pptImages\slide-18.png'
        AsyncImage:
            source: 'pptImages\slide-19.png'

    Button:
        text: "Home"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0, "top":0.09}
        on_press:
            root.manager.current = "Home"
    Button:
        text: "Resources"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0.33, "top":0.09}
        on_press:
            root.manager.current = "Resources"
    Button:
        text: "Daily Quote"
        size_hint: 0.335, 0.1
        pos_hint: {"x":0.66, "top":0.09}
        on_press:
            root.manager.current = "Daily Quote"

<LocalResourcesScreen>
    name: "Local Resources"
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            pos:
            size: self.size
    Image:
        source: "LoadBackground.png"
        size_hint: 0.3, 0.3
        pos_hint: {"x":0.35, "top":0.65}

    FloatLayout:
        Label:
            text: "Local Providers"
            color: 0,0,0,1
            font_size: '32sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":1}

        Label:
            text: "[ref=<str>][u]Triad Therapy LLC[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.9}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.triadtherapy.com/")
        Label:
            text: "[ref=<str>][u]NHTC | New Horizons Treatment Center | United States[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.85}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.newhorizonstreatment.org/")
        Label:
            text: "[ref=<str>][u]Therapy \ Asheboro, NC (abmnc.com)[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.8}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("http://www.abmnc.com/")
        Label:
            text: "[ref=<str>][u]Home | Asheboro Counseling & Wellness[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.75}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.asheborocounseling.com/")
        Label:
            text: "[ref=<str>][u]Daymark Recovery Services - Asheboro Center[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.7}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.daymarkrecovery.org/locations/asheboro-center")
        Label:
            text: "[ref=<str>][u]RedBud Legacy – A Place to Discover Your Legacy[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.65}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://redbudlegacy.com/")
        Label:
            text: "[ref=<str>][u]Daymark Recovery Services - Archdale Center[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.6}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.daymarkrecovery.org/locations/archdale-center")
        Label:
            text: "[ref=<str>][u]Contact - Family Solutions (famsolutions.org)[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.55}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.famsolutions.org/contact")
        Label:
            text: "[ref=<str>][u]Haven Counseling Group – Sometimes Listening Needs a Third Person[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.5}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://havencounselinggroup.org/")
        Label:
            text: "[ref=<str>][u]Morrow Office – Youth Unlimited Inc[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.45}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://youthunlimited.cc/?page_id=1693")
        Label:
            text: "Cardinal Clinic, LLC  336.318.2760   Asheboro, NC\n\nSteps for Change Behavioral  (336) 824-2171  Ramseur, NC\n\nWildflower Counseling and Consulting, PLLC  (336) 937-0716   Ramseur, NC"
            halign: 'center'
            color: 0,0,0,1
            font_size: '12sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.35}
        Label:
            text: "[ref=<str>][u]Support Groups/Facilities[/u][/ref]"
            color: 0,0,0.55,1
            font_size: '20sp'
            size_hint: 0.1, 0.2
            pos_hint: {"x":0.45, "top":0.25}
            markup: True
            on_ref_press:
                import webbrowser
                webbrowser.open("https://www.randolphfcc.org/")




    Button:
        text: "Home"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0, "top":0.09}
        on_press:
            root.manager.current = "Home"
    Button:
        text: "Resources"
        size_hint: 0.333, 0.1
        pos_hint: {"x":0.33, "top":0.09}
        on_press:
            root.manager.current = "Resources"
    Button:
        text: "Daily Quote"
        size_hint: 0.335, 0.1
        pos_hint: {"x":0.66, "top":0.09}
        on_press:
            root.manager.current = "Daily Quote"

<QuoteScreen>:
    name: "Daily Quote"
    canvas:
        Color:
            rgba: 1, 0.77, 0.88, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Image:
        source: "LoadBackground.png"
        size_hint: 0.3, 0.3
        pos_hint: {"x": 0.35, "top": 0.65}

    FloatLayout:
        Label:
            id: quote_label  # Identifier for updating the quote dynamically
            text: "Your daily quote will appear here."
            color: 0, 0, 0, 1
            font_size: '20sp'
            size_hint: 0.8, 0.4
            pos_hint: {"center_x": 0.5, "center_y": 0.6}
            text_size: self.width, None
            halign: "center"
            valign: "middle"

        Button:
            text: "Refresh Quote"
            size_hint: 0.5, 0.1
            pos_hint: {"center_x": 0.5, "center_y": 0.4}
            on_press: root.display_random_quote()  # Call the method to update the quote

    Button:
        text: "Home"
        size_hint: 0.333, 0.1
        pos_hint: {"x": 0, "top": 0.09}
        on_press:
            root.manager.current = "Home"
            root.manager.transition.direction = "right"
    Button:
        text: "Resources"
        size_hint: 0.333, 0.1
        pos_hint: {"x": 0.33, "top": 0.09}
        on_press:
            root.manager.current = "Resources"
            root.manager.transition.direction = "right"
    Button:
        text: "Daily Quote"
        size_hint: 0.335, 0.1
        pos_hint: {"x": 0.66, "top": 0.09}

