<ScreenManagement>:
    transition:
    LoadingScreen:
    HomeScreen:

<LoadingScreen>:
    name: "Load"
    Image:
        source: "LoadBackground.png"

    FloatLayout:
        Label:
            text: "RelaxED"
            color: 1,1,1,1
            font_size: '32sp'
            size: 100,200
            pos:

<HomeScreen>:
    name: 'Home'
    Image:
        source: "LoadBackground.png"


<ResourceScreen>:
    name: "Resources"

<QuoteScreen>:
    name: "Daily Quote"