name: Build
on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: .
          workdir: .
          buildozer_version: 1.4.0  # Specify a stable version